### ISSUE TITLE
Provide example how to use sorting & filters

### ISSUE THREAD

**Issue by od3n** [esbenp/bruno#11]

**Comment by esbenp** [comment]
Could you maybe elaborate a bit? There already is an example in the readme file https://github.com/esbenp/bruno#examples 

Could you be more specific as to what you feel is missing?

**Comment by od3n** [comment]
i'm using postman to test my api. should i pass the sort[] params as url parameters? mind to share your example request for filters & sorting

**Comment by od3n** [comment]
@esbenp nevermind, just figured out the way.

i should pass the array key too.

so it will be something like this :

?sort[0][key]=title&sort[0][direction]=ASC

**Comment by marcospaegle** [comment]
I think the exemples could be more explicit.

**Comment by mjza** [comment]
How can we use custom sort functions?

**Comment by mjza** [comment]
I discovered. Here is an example for custom sort function while it was not mentioned in the documentations!

```php
    public function sortComments(Builder $query, $direction){
        call_user_func([$query, 'orderBy'], 'comments.order', $direction);
    }
```
