### ISSUE TITLE
Feature Request: ability to filter using 'between' method

### ISSUE THREAD

**Issue by pmccarren** [esbenp/bruno#21]

**Comment by pmccarren** [comment]
Looks like `between` support was half implemented and then removed. Conversation in #24 / (https://github.com/esbenp/bruno/pull/24#issuecomment-321071615)

**Comment by Carghaez** [comment]
Why implement "between" operator when you can have the same functionality through the combination of:
- gte + lte
- gt + lte
- gte + lt
- gt + lt
