### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::getQualifiedForeignKeyName()

### ISSUE THREAD

**Issue by simonpeters** [esbenp/bruno#25]
I'm getting an error when trying to use filter on relationships

```Call to undefined method Illuminate\Database\Query\Builder::getQualifiedForeignKeyName()```

The error seems to come from [ line 255](https://github.com/esbenp/bruno/blob/master/src/EloquentBuilderTrait.php#L255) of EloquentBuilderTrait.

 Anyone else have this issue?

**Comment by simonpeters** [comment]
If I change ```getQualifiedForeignKeyName```to ```getQualifiedForeignKey``` it seems to work.

**Comment by esbenp** [comment]
What version of Laravel are you using?

**Comment by simonpeters** [comment]
v5.4.35

**Comment by esbenp** [comment]
What kind of relation is throwing the error?

**Comment by mvilera** [comment]
i'm having the same error, on same laravel version, my relation is like this:

```php
public function staff()
{
    return $this->belongsTo(User::class);
}
```

**Comment by nickrigby** [comment]
If you're using Laravel 5.5, it's because of two functions that wee renamed, detailed here:
[https://github.com/laravel/framework/issues/20869#issuecomment-326334760](https://github.com/laravel/framework/issues/20869#issuecomment-326334760)

**Comment by mvilera** [comment]
Noup, i'm using 5.4.

**Comment by sfakir** [comment]
Okay, we are using 5.5 how do I change the method?
