### ISSUE TITLE
Filter_groups Example

### ISSUE THREAD

**Issue by akoSalman** [esbenp/bruno#26]
Can anyone give an example of filter_groups please?
I don't know how to pass filter_group's options in url.
I use it like below, but does not work:
`By clicking on the link, show questions that have answer with specified id.`
```HTML
<a class="btn btn-default" href="questions?Filter_groups=[{"or":false,"filters":[["answer", "eq",{{ $answer->id }}],]}]">Show Questions That Have This Answer</a><
```
In fact i want to pass this data :
```json
[
    {
        "or": false,
        "filters": [
            ["answer", "eq", "id"],
        ]
    }
]
```

**Comment by pmccarren** [comment]
You have to stringify the params to make them URL safe. A utility like [QS](https://www.npmjs.com/package/qs) should do exactly what you're looking for. All you'd have to do is pass the params through the QS.stringify method and bingo!

**Comment by akoSalman** [comment]
Thankyou @pmccarren for your answer.
I used [QS](https://www.npmjs.com/package/qs#stringifying) like below and solved my problem:
```js
var qs = require('qs');
 
var str = qs.stringify({
	filter_groups :
	[
	    {
	        "or": false,
	        "filters": [
	            ["answer", "eq", "id"],
	        ]
	    }
	]
}
, { encode: false });

console.log(str); 
```
Output is `filter_groups[0][or]=false&filter_groups[0][filters][0][0]=answer&filter_groups[0][filters][0][1]=eq&filter_groups[0][filters][0][2]=id`
