### ISSUE TITLE
Support for laravel 6

### ISSUE THREAD

**Issue by uddhab** [esbenp/bruno#51]

**Comment by pmccarren** [comment]
I plan to start work on this in the near future. Happy to collab if anyone else is already working on it!

**Comment by chrisgillis** [comment]
Also looking for this, +1

**Comment by nscharrenberg** [comment]
Was also looking for this.
Forked the repo and updated the composer file with the latest requirement versions (require and require-dev).

Also had to remove `syntaxCheck` in `phpunit.xml` as it's deprecated on later versions of phpunit and had to change the composer package for `satooshi/php-coveralls`, as that one seems to be deprecated and moved to `php-coveralls/php-coveralls`

Besides making bruno compatible i also had to make architect compatible with laravel 6.
Pretty much the same changes as the bruno composer file.

Haven't made a PR yet as i'm not sure if the php-coveralls works and I haven't been able to test the code coverage yet (should be the same as the current code coverage, as all tests seem to pass).

Repo's can be found here:
[https://github.com/nscharrenberg/architect](architect)
[https://github.com/nscharrenberg/bruno](bruno)

**Comment by esbenp** [comment]
Hey guys, we will soon upgrade our own repo to 6.0 so I will get to it then

**Comment by EnnioWolsink** [comment]
@esbenp Any timeframe on this? Would love to be able to use this soon.

**Comment by chrisgillis** [comment]
@esbenp Still looking to add 6.0 support soon? Need any help?

**Comment by johnzenza** [comment]
@esbenp Any update on this one?

**Comment by gentritabazi01** [comment]
Check this for Laravel new version:

https://github.com/one2tek/larapi

**Comment by esbenp** [comment]
Please try `6.0.0`
