### ISSUE TITLE
Laravel 7 suport?

### ISSUE THREAD

**Issue by allanvobraun** [esbenp/bruno#60]
Hello, its possible to install this package in laravel version 7?
I'm trying to install it with composer and its not working :(.
Composer output:

Problem 1
    - Conclusion: remove laravel/framework v7.18.0
    - Conclusion: don't install laravel/framework v7.18.0
    - optimus/bruno 3.0.0 requires laravel/framework ~5.4 -> satisfiable by laravel/framework[5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev].
    - optimus/bruno 3.1.0 requires laravel/framework ~5.4 -> satisfiable by laravel/framework[5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev].
    - Can only install one of: laravel/framework[5.5.x-dev, v7.18.0].
    - Can only install one of: laravel/framework[5.6.x-dev, v7.18.0].
    - Can only install one of: laravel/framework[5.7.x-dev, v7.18.0].
    - Can only install one of: laravel/framework[5.8.x-dev, v7.18.0].
    - Can only install one of: laravel/framework[5.4.x-dev, v7.18.0].
    - Installation request for laravel/framework (locked at v7.18.0, required as ^7.0) -> satisfiable by laravel/framework[v7.18.0].
    - Installation request for optimus/bruno ~3.0 -> satisfiable by optimus/bruno[3.0.0, 3.1.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by rossco555** [comment]
Also interested in this.

**Comment by gentritabazi01** [comment]
Check this:

https://github.com/one2tek/larapi

**Comment by esbenp** [comment]
Please try `6.0.0`
